### ISSUE TITLE
Recursive promise resolution

### ISSUE THREAD

**Issue by Rush** [d6u/fun-http#1]
Nice project, you want to add support for deeply resolving promises (recursively) - https://github.com/virtkick/promise-resolve-deep

this allows to do things like:

``` js
return {
  entities: Promise.map(smth, mapAsynchronously), // this may return a list of objects which can have promises as as key-values all of which will be resolved properly
};
```

**Comment by d6u** [comment]
Thanks. This looks like some I should add!

**Comment by d6u** [comment]
@Rush Thanks for your suggestion! Now nested promise resolve is supported by recursively finding promises on object properties. See test case https://github.com/d6u/fun-http/blob/bf992e7512407b8b82dc4347e71a1998c2a1600a/test/FunHttp.test.js#L84-L88
