### ISSUE TITLE
Returning custom HTTP response code

### ISSUE THREAD

**Issue by tracker1** [d6u/fun-http#2]
Generally for calls, you should return the appropriate HTTP status code, namely 4xx responses for invalid input...  There doesn't seem to be a way to return a 400, 404, etc...

[0] https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by d6u** [comment]
@tracker1 Thanks! It's actually already supported, I just didn't document it. Here is the new document https://github.com/d6u/fun-http#customize-response, see the **Customize Response** section.

**Comment by d6u** [comment]
@tracker1 Thanks for your comment. I added some test cases to demonstrate this is supported.
https://github.com/d6u/fun-http/blob/bf992e7512407b8b82dc4347e71a1998c2a1600a/test/FunHttp.test.js#L104-L106
