### ISSUE TITLE
export as a typescript module

### ISSUE THREAD

**Issue by danielepolencic** [d6u/fun-http#4]
**DISCLAIMER**: Perhaps I just misunderstood how Typescript module loader works, but...

when I try to import `fun-http` as an es6 module, the module is not recognised:

![image](https://cloud.githubusercontent.com/assets/1130499/16205492/0533f474-371c-11e6-9f19-f746096c23ff.png)

this is because there's no module declaration in the definition files. From what I understood, to use `fun-http` as an es6 module, you'd need to have something similar this in your code:

``` typescript
declare module 'fun-http' {
  export class MyClass { /* ... */ }
}
```

In all this examples, my `tsconfig.json` was configured like this:

``` json
{
  "files": [
    "node_modules/fun-http/lib/FunHttp.d.ts"
  ]
}
```

I'm happy to submit a PR _if this is the right thing_.

**Comment by d6u** [comment]
Hey @danielepolencic, thanks for noticing this. I have published a new version fixing the export format. You should be able to just import it. You don't even have to include `"node_modules/fun-http/lib/FunHttp.d.ts"` inside your tsconfig.json. TypeScript compiler should figure out what's the typing automatically. Check out https://github.com/d6u/fun-http/releases/tag/v0.2.1 for detail.

Let me know whether this works for you.

**Comment by danielepolencic** [comment]
It worked! Thanks
